const DEFAULT_STYLES = {
    LIST_CONTAINER_PADDING: 0,
    SCREEN_CONTAINER_PADDING: 20,
    PRIMARY_COLOR: '#FF5722',
    PRIMARY_BORDER_COLOR: '#5D4037',
    TEXT_COLOR_INVERSE: '#FFF'
};

export default DEFAULT_STYLES;
