const DEFAULT_STYLES = {
    LIST_CONTAINER_PADDING: 0,
    SCREEN_CONTAINER_PADDING: 20,
    PRIMARY_COLOR_DARK: '#0097A7',
    PRIMARY_COLOR: '#00BCD4',
    PRIMARY_COLOR_LIGHT: '#B2EBF2',
    SECONDARY_COLOR: '#FF9800',
    PRIMARY_TEXT_COLOR: '#212121',
    SECONDARY_TEXT_COLOR: '#757575',
    DIVIDER_COLOR: '#BDBDBD',
    PRIMARY_BORDER_COLOR: '#5D4037',
    SECONDARY_BODER_COLOR: '#FFCCBC',
    TEXT_COLOR_INVERSE: '#FFF'
};

export default DEFAULT_STYLES;
