const DEFAULT_STYLES = {
    LIST_CONTAINER_PADDING: 0,
    SCREEN_CONTAINER_PADDING: 20,
    PRIMARY_COLOR_DARK: '#FFA000',
    PRIMARY_COLOR: '#FFC107',
    PRIMARY_COLOR_LIGHT: '#FFECB3',
    SECONDARY_COLOR: '#FF5722',
    PRIMARY_TEXT_COLOR: '#212121',
    SECONDARY_TEXT_COLOR: '#757575',
    DIVIDER_COLOR: '#BDBDBD',
    PRIMARY_BORDER_COLOR: '#5D4037',
    TEXT_COLOR_INVERSE: '#FFF'
};

export default DEFAULT_STYLES;
